# Allow unauthenticated read of cluster-info for kubeadm join discovery.
# See: configmaps "cluster-info" forbidden User "system:anonymous"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeadm:cluster-info
  namespace: kube-public
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cluster-info"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeadm:cluster-info
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeadm:cluster-info
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:unauthenticated
