apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-scan
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scan
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-scan
  template:
    metadata:
      labels:
        app: kube-scan
    spec:
      serviceAccountName: kube-scan
      containers:
      - name: kube-scan
        image: octarinesec/kube-scan:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kube-scan-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: kube-scan
  ports:
    - port: 8080
      nodePort: 30800
